apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: webserver
    tier: webserver
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: dimitatu/goo
        name: webserver
        ports:
          - containerPort: 8080


# apiVersion: v1
# kind: Pod
# metadata:
#   labels:
#     run: webserver
#   name: webserver
# spec:
#   containers:
#   - image: dimitatu/goo
#     name: webserver
#     ports:
#       - containerPort: 8080
